#!/usr/bin/env bash
# Idempotently ensure a PR exists from claude/ci-demo to the default branch.
# Prints the PR URL (existing or newly-created). Never creates duplicates —
# safe to call from every Skill on every run.
#
# Usage: ensure_pr.sh
set -euo pipefail

DEFAULT=$(gh repo view --json defaultBranchRef --jq '.defaultBranchRef.name')
EXISTING=$(gh pr list --head claude/ci-demo --base "$DEFAULT" --json url --jq '.[0].url // empty')

if [ -n "$EXISTING" ]; then
    echo "$EXISTING"
    exit 0
fi

gh pr create \
    --base "$DEFAULT" \
    --head claude/ci-demo \
    --title "CI: workflows from Claude" \
    --body "Generated by Claude Skills (lint-and-test, dependency-audit, security-scan, build-and-release)."
