#!/usr/bin/env bash
# Idempotently ensure a PR exists from the demo branch to the default branch.
# Prints the PR URL (existing or newly-created). Never creates duplicates —
# safe to call from every Skill on every run.
#
# Branch name comes from DEMO_BRANCH (set by the orchestrator per pipeline
# run). Falls back to claude/ci-demo for backward compat with the legacy
# single-shared-branch path.
#
# Usage: ensure_pr.sh
set -euo pipefail

BRANCH="${DEMO_BRANCH:-claude/ci-demo}"
DEFAULT=$(gh repo view --json defaultBranchRef --jq '.defaultBranchRef.name')
EXISTING=$(gh pr list --head "$BRANCH" --base "$DEFAULT" --json url --jq '.[0].url // empty')

if [ -n "$EXISTING" ]; then
    echo "$EXISTING"
    exit 0
fi

gh pr create \
    --base "$DEFAULT" \
    --head "$BRANCH" \
    --title "CI: workflows from Claude ($BRANCH)" \
    --body "Generated by Claude Skills (lint-and-test, dependency-audit, security-scan, build-and-release)."
